-- CuidaMed: schema inicial (PostgreSQL). Ver ADR-0045.
--
-- Ids são IDENTITY "BY DEFAULT" para podermos inserir os ids que já existem nos CSV
-- na migração; depois da carga, reajustar as sequências (script de migração).
--
-- criado_em / atualizado_em / excluido_em existem para a sincronização do app offline:
-- a exclusão é lógica (excluido_em preenchido), para o servidor conseguir descartar
-- edições que cheguem depois de uma exclusão (excluir pesa mais que editar).

CREATE TABLE usuario (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo           VARCHAR(10)  NOT NULL CHECK (tipo IN ('IDOSO', 'FAMILIAR')),
    nome           VARCHAR(150) NOT NULL,
    email          VARCHAR(254) NOT NULL,
    senha_hash     VARCHAR(100) NOT NULL,  -- BCrypt, nunca a senha em texto puro
    criado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    excluido_em    TIMESTAMPTZ
);

-- E-mail único sem diferenciar maiúsculas/minúsculas, entre contas não excluídas.
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email)) WHERE excluido_em IS NULL;

-- Vínculo idoso <-> familiar. O familiar solicita, o idoso aceita.
-- Pedido PENDENTE expira em 24 h (calculado a partir de solicitado_em, no código).
CREATE TABLE vinculo (
    idoso_id      INTEGER     NOT NULL REFERENCES usuario (id),
    familiar_id   INTEGER     NOT NULL REFERENCES usuario (id),
    status        VARCHAR(10) NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'ACEITO', 'RECUSADO')),
    solicitado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    respondido_em TIMESTAMPTZ,
    PRIMARY KEY (idoso_id, familiar_id),
    CHECK (idoso_id <> familiar_id)
);

CREATE INDEX ix_vinculo_familiar ON vinculo (familiar_id);

CREATE TABLE medicamento (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idoso_id       INTEGER      NOT NULL REFERENCES usuario (id),
    nome           VARCHAR(150) NOT NULL,
    horario        TIME         NOT NULL,
    dia_semana     VARCHAR(9)   NOT NULL CHECK (dia_semana IN
                       ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    tipo           VARCHAR(10)  NOT NULL CHECK (tipo IN ('COMPRIMIDO', 'GOTAS', 'INJECAO', 'OUTRO')),
    criado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    excluido_em    TIMESTAMPTZ
);

CREATE INDEX ix_medicamento_idoso ON medicamento (idoso_id) WHERE excluido_em IS NULL;

-- Histórico de tomadas: só recebe inserções (não gera conflito na sincronização).
CREATE TABLE historico (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicamento_id   INTEGER   NOT NULL REFERENCES medicamento (id),
    idoso_id         INTEGER   NOT NULL REFERENCES usuario (id),
    data_hora_tomada TIMESTAMP NOT NULL,  -- LocalDateTime do domínio, sem fuso
    foi_tomado       BOOLEAN   NOT NULL,
    criado_em        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_historico_idoso ON historico (idoso_id, data_hora_tomada DESC);
CREATE INDEX ix_historico_medicamento ON historico (medicamento_id);
